// Mock data for SMEs
export const smes = [
  {
    id: 1,
    name: "Batik Sekar Arum",
    logo: "/placeholder.svg?height=200&width=200&text=Batik+Sekar",
    coverImage: "/placeholder.svg?height=300&width=1200&text=Batik+Sekar+Arum",
    shortDescription: "Batik tradisional dengan sentuhan modern dari Yogyakarta",
    description:
      "Batik Sekar Arum adalah UMKM yang fokus pada pembuatan batik tradisional dengan sentuhan modern. Didirikan pada tahun 2010 di Yogyakarta, kami memproduksi berbagai jenis batik dengan motif khas yang terinspirasi dari kekayaan budaya Indonesia.",
    story:
      "Berawal dari kecintaan terhadap batik tradisional, pendiri kami Ibu Sekar memulai usaha kecil-kecilan di rumahnya. Seiring berjalannya waktu, kualitas dan keunikan batik buatannya mulai dikenal dan diminati banyak orang. Kini Batik Sekar Arum telah berkembang menjadi UMKM yang mempekerjakan lebih dari 20 pengrajin lokal.",
    city: "Yogyakarta",
    province: "DI Yogyakarta",
    address: "Jl. Malioboro No. 123, Yogyakarta",
    phone: "+62812345678",
    email: "info@batiksekararum.id",
    website: "https://batiksekararum.id",
    instagram: "batiksekararum",
    facebook: "https://facebook.com/batiksekararum",
    establishedDate: "2010-05-15",
    category: "Fashion & Tekstil",
    featured: true,
    productCount: 24,
  },
  {
    id: 2,
    name: "Keramik Tanah Liat",
    logo: "/placeholder.svg?height=200&width=200&text=Keramik",
    coverImage: "/placeholder.svg?height=300&width=1200&text=Keramik+Tanah+Liat",
    shortDescription: "Kerajinan keramik handmade dari tanah liat Jepara",
    description:
      "Keramik Tanah Liat adalah UMKM yang bergerak di bidang kerajinan keramik handmade. Berlokasi di Jepara, Jawa Tengah, kami menghasilkan berbagai produk keramik berkualitas tinggi dengan desain yang unik dan estetik.",
    city: "Jepara",
    province: "Jawa Tengah",
    address: "Jl. Keramik No. 45, Jepara",
    phone: "+62823456789",
    email: "halo@keramiktanahliat.id",
    establishedDate: "2015-08-20",
    category: "Kerajinan",
    featured: true,
    productCount: 18,
  },
  {
    id: 3,
    name: "Kopi Nusantara",
    logo: "/placeholder.svg?height=200&width=200&text=Kopi",
    coverImage: "/placeholder.svg?height=300&width=1200&text=Kopi+Nusantara",
    shortDescription: "Kopi single origin dari berbagai daerah di Indonesia",
    description:
      "Kopi Nusantara adalah UMKM yang bergerak di bidang pengolahan dan penjualan kopi single origin dari berbagai daerah di Indonesia. Kami berkomitmen untuk mendukung petani kopi lokal dan mempromosikan kekayaan cita rasa kopi Indonesia.",
    city: "Bandung",
    province: "Jawa Barat",
    address: "Jl. Braga No. 67, Bandung",
    phone: "+62834567890",
    email: "hello@kopinusantara.id",
    instagram: "kopinusantara.id",
    establishedDate: "2018-03-10",
    category: "Makanan & Minuman",
    featured: true,
    productCount: 12,
  },
  {
    id: 4,
    name: "Anyaman Bambu Hijau",
    logo: "/placeholder.svg?height=200&width=200&text=Anyaman",
    coverImage: "/placeholder.svg?height=300&width=1200&text=Anyaman+Bambu",
    shortDescription: "Kerajinan anyaman bambu ramah lingkungan dari Bali",
    description:
      "Anyaman Bambu Hijau adalah UMKM yang memproduksi berbagai kerajinan anyaman bambu yang ramah lingkungan. Berlokasi di Bali, kami menggabungkan teknik tradisional dengan desain modern untuk menciptakan produk yang fungsional dan estetik.",
    city: "Ubud",
    province: "Bali",
    address: "Jl. Monkey Forest No. 89, Ubud",
    phone: "+62845678901",
    email: "info@anyamanbambuhijau.id",
    establishedDate: "2017-11-05",
    category: "Kerajinan",
    productCount: 15,
  },
  {
    id: 5,
    name: "Tenun Songket Palembang",
    logo: "/placeholder.svg?height=200&width=200&text=Tenun",
    coverImage: "/placeholder.svg?height=300&width=1200&text=Tenun+Songket",
    shortDescription: "Kain tenun songket tradisional dari Palembang",
    description:
      "Tenun Songket Palembang adalah UMKM yang melestarikan dan mengembangkan kerajinan tenun songket tradisional Palembang. Kami memproduksi berbagai jenis kain songket dengan motif khas yang diwariskan secara turun-temurun.",
    city: "Palembang",
    province: "Sumatera Selatan",
    address: "Jl. Sudirman No. 123, Palembang",
    phone: "+62856789012",
    email: "info@tenunsongket.id",
    instagram: "tenunsongket",
    establishedDate: "2008-07-22",
    category: "Fashion & Tekstil",
    productCount: 20,
  },
]

// Mock data for products
export const products = [
  {
    id: 1,
    name: "Kemeja Batik Parang",
    description: "Kemeja batik dengan motif parang klasik",
    longDescription:
      "Kemeja batik dengan motif parang klasik yang dibuat dengan teknik batik tulis. Menggunakan kain katun premium yang nyaman dipakai dan pewarna alami yang ramah lingkungan. Cocok untuk acara formal maupun semi-formal.",
    price: 350000,
    image: "/placeholder.svg?height=500&width=500&text=Kemeja+Batik",
    categorySlug: "fashion",
    smeId: 1,
    featured: true,
    createdAt: "2023-01-15",
  },
  {
    id: 2,
    name: "Dress Batik Kawung",
    description: "Dress batik dengan motif kawung modern",
    longDescription:
      "Dress batik dengan motif kawung yang didesain dengan gaya modern. Menggunakan kain rayon yang jatuh dan nyaman dipakai. Cocok untuk acara formal maupun casual.",
    price: 450000,
    image: "/placeholder.svg?height=500&width=500&text=Dress+Batik",
    categorySlug: "fashion",
    smeId: 1,
    featured: false,
    createdAt: "2023-02-20",
  },
  {
    id: 3,
    name: "Vas Bunga Keramik",
    description: "Vas bunga keramik handmade dengan motif geometris",
    longDescription:
      "Vas bunga keramik yang dibuat secara handmade dengan motif geometris. Setiap vas memiliki keunikan tersendiri karena dibuat satu per satu oleh pengrajin kami. Cocok untuk menghias ruangan atau sebagai hadiah spesial.",
    price: 275000,
    image: "/placeholder.svg?height=500&width=500&text=Vas+Keramik",
    categorySlug: "home-decor",
    smeId: 2,
    featured: true,
    createdAt: "2023-03-05",
  },
  {
    id: 4,
    name: "Set Cangkir Keramik",
    description: "Set 4 cangkir keramik dengan tekstur alami",
    longDescription:
      "Set 4 cangkir keramik dengan tekstur alami yang dibuat secara handmade. Menggunakan tanah liat berkualitas tinggi dan glasir food-grade yang aman. Cocok untuk menikmati teh atau kopi di rumah.",
    price: 320000,
    image: "/placeholder.svg?height=500&width=500&text=Cangkir+Keramik",
    categorySlug: "home-decor",
    smeId: 2,
    featured: false,
    createdAt: "2023-03-15",
  },
  {
    id: 5,
    name: "Kopi Arabika Gayo",
    description: "Kopi arabika single origin dari Aceh Gayo",
    longDescription:
      "Kopi arabika single origin dari dataran tinggi Gayo, Aceh. Memiliki cita rasa fruity dengan hint of chocolate dan keasaman yang seimbang. Biji kopi dipetik dan disortir secara manual untuk menjamin kualitas terbaik.",
    price: 125000,
    image: "/placeholder.svg?height=500&width=500&text=Kopi+Gayo",
    categorySlug: "food-beverage",
    smeId: 3,
    featured: true,
    createdAt: "2023-04-10",
  },
  {
    id: 6,
    name: "Kopi Robusta Toraja",
    description: "Kopi robusta single origin dari Toraja",
    longDescription:
      "Kopi robusta single origin dari pegunungan Toraja, Sulawesi Selatan. Memiliki body yang kuat dengan hint of spice dan dark chocolate. Sangat cocok untuk penikmat kopi dengan karakter bold.",
    price: 110000,
    image: "/placeholder.svg?height=500&width=500&text=Kopi+Toraja",
    categorySlug: "food-beverage",
    smeId: 3,
    featured: false,
    createdAt: "2023-04-25",
  },
  {
    id: 7,
    name: "Keranjang Bambu",
    description: "Keranjang anyaman bambu multifungsi",
    longDescription:
      "Keranjang anyaman bambu yang dapat digunakan untuk berbagai keperluan, seperti menyimpan buah, roti, atau sebagai elemen dekorasi. Dibuat dari bambu pilihan yang kuat dan tahan lama.",
    price: 185000,
    image: "/placeholder.svg?height=500&width=500&text=Keranjang+Bambu",
    categorySlug: "home-decor",
    smeId: 4,
    featured: true,
    createdAt: "2023-05-05",
  },
  {
    id: 8,
    name: "Tas Anyaman Bambu",
    description: "Tas anyaman bambu untuk gaya casual",
    longDescription:
      "Tas anyaman bambu yang stylish dan ramah lingkungan. Cocok untuk gaya casual sehari-hari atau untuk ke pantai. Dilengkapi dengan lapisan kain di bagian dalam dan tali yang nyaman.",
    price: 250000,
    image: "/placeholder.svg?height=500&width=500&text=Tas+Bambu",
    categorySlug: "fashion",
    smeId: 4,
    featured: false,
    createdAt: "2023-05-20",
  },
  {
    id: 9,
    name: "Kain Songket Palembang",
    description: "Kain songket tradisional motif bunga mawar",
    longDescription:
      "Kain songket tradisional Palembang dengan motif bunga mawar yang dibuat dengan benang emas. Setiap kain ditenun secara manual dengan ketelitian tinggi. Cocok untuk acara adat atau sebagai koleksi.",
    price: 1500000,
    image: "/placeholder.svg?height=500&width=500&text=Songket+Palembang",
    categorySlug: "fashion",
    smeId: 5,
    featured: true,
    createdAt: "2023-06-10",
  },
  {
    id: 10,
    name: "Selendang Songket",
    description: "Selendang songket dengan motif geometris",
    longDescription:
      "Selendang songket dengan motif geometris yang elegan. Dibuat dengan benang sutra berkualitas tinggi dan benang emas. Cocok untuk melengkapi busana tradisional atau sebagai aksesoris fashion.",
    price: 750000,
    image: "/placeholder.svg?height=500&width=500&text=Selendang+Songket",
    categorySlug: "fashion",
    smeId: 5,
    featured: false,
    createdAt: "2023-06-25",
  },
]

// Mock data for categories
export const categories = [
  {
    id: 1,
    name: "Fashion",
    slug: "fashion",
    image: "/placeholder.svg?height=200&width=200&text=Fashion",
  },
  {
    id: 2,
    name: "Dekorasi Rumah",
    slug: "home-decor",
    image: "/placeholder.svg?height=200&width=200&text=Dekorasi",
  },
  {
    id: 3,
    name: "Makanan & Minuman",
    slug: "food-beverage",
    image: "/placeholder.svg?height=200&width=200&text=Makanan",
  },
  {
    id: 4,
    name: "Kerajinan",
    slug: "crafts",
    image: "/placeholder.svg?height=200&width=200&text=Kerajinan",
  },
  {
    id: 5,
    name: "Aksesoris",
    slug: "accessories",
    image: "/placeholder.svg?height=200&width=200&text=Aksesoris",
  },
  {
    id: 6,
    name: "Seni",
    slug: "art",
    image: "/placeholder.svg?height=200&width=200&text=Seni",
  },
]
